package gcode

const TOKEN_EOF = -1
const TOKEN_SLEW = 0
const TOKEN_MACHINE = 1
const TOKEN_CWMOVE_2D = 2
const TOKEN_CCWMOVE_2D = 3
const TOKEN_DWELL = 4

const TOKEN_FIND_HOME = 37
const TOKEN_INCHES_PROGRAMMING = 70
const TOKEN_MILLIMETERS_PROGRAMMING = 71

const TOKEN_CWMOVE_3D = 72
const TOKEN_CCWMOVE_3D = 73
const TOKEN_ARC_INCREMENTAL_MODE = 74
const TOKEN_ARC_ABSOLUTE_MODE = 75

const TOKEN_ONE_STROKE_DRILL_CYCLE = 81
const TOKEN_PECK_DRILL_CYCLE = 83
const TOKEN_TAP_DRILL_CYCLE = 84

const TOKEN_ABSOLUTE_COORDINATE_MODE = 90
const TOKEN_INCREMENTAL_COORDINATE_MODE = 91
const TOKEN_SOFT_HOME = 92
const TOKEN_SPINDLE_SPEED = 97
